# Cloud Build 구성
# Electron 데스크톱 앱 빌드 및 Cloud Storage 배포

substitutions:
  _GCS_BUCKET: "gknu-dohan-k764-knowledge-graph-data"  # Cloud Storage 버킷
  _CLOUD_RUN_URL: "https://knowledge-graph-api-xxxxx-xx.a.run.app"  # Cloud Run URL (실제 URL로 변경 필요)

steps:
  # 1. Node.js 설치 및 의존성 설치
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        npm ci

  # 2. Electron 메인 프로세스 빌드
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        npm run build:electron

  # 3. 환경 변수 파일 생성 (Cloud Run URL 설정)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        # Cloud Run URL에서 WebSocket URL 생성
        WS_URL=$${_CLOUD_RUN_URL/https:\/\//wss:\/\/}
        WS_URL=$${WS_URL/http:\/\//ws:\/\/}
        echo "VITE_WS_URL=$${WS_URL}/ws" > .env.production
        cat .env.production

  # 4. Vite 빌드 (환경 변수 포함)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        npm run build:vite

  # 5. Electron 빌드 (Windows용)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        npm run build
        ls -la release/

  # 6. Cloud Storage에 업로드
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/desktop
        gsutil -m cp -r release/* gs://${_GCS_BUCKET}/desktop-app/v${TAG_NAME:-latest}/

  # 7. 다운로드 링크 생성 (메타데이터 파일)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > /tmp/latest.json << EOF
        {
          "version": "${TAG_NAME:-latest}",
          "windows": {
            "installer": "Knowledge Graph Setup ${TAG_NAME:-latest}.exe",
            "url": "https://storage.googleapis.com/${_GCS_BUCKET}/desktop-app/v${TAG_NAME:-latest}/Knowledge Graph Setup ${TAG_NAME:-latest}.exe"
          },
          "buildDate": "$$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        }
        EOF
        gsutil cp /tmp/latest.json gs://${_GCS_BUCKET}/desktop-app/latest.json
        gsutil acl ch -u AllUsers:R gs://${_GCS_BUCKET}/desktop-app/latest.json
        gsutil acl ch -r -u AllUsers:R gs://${_GCS_BUCKET}/desktop-app/v${TAG_NAME:-latest}/

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'

